#!/usr/bin/env python


class FifoQueue(object):
    """FIFO queue made out of two stacks.
    
    """
    
    def __init__(self):
        input_stack = []
        output_stack = []
    
    def enqueue(self):
        pass
    
    def dequeue(self):
        pass

if __name__ == '__main__':
    # Problem 1:
    # Create a FIFO queue using only stacks.
    
    # Problem 2:
    # Create a stack using only FIFO queues.
    
    # Problem 3:
    # Implement singly linked list.
    
    # Problem 4:
    # Implement a doubly linked list.
    pass