#!/usr/bin/env python


if __name__ == '__main__':
    # Problem 1:
    # Create a FIFO queue using only stacks.
    
    # Problem 2:
    # Create a stack using only FIFO queues.
    
    # Problem 3:
    # Implement singly linked list.
    
    # Problem 4:
    # Implement a doubly linked list.